### ISSUE TITLE
Issue with Plaid-Sync

### ISSUE THREAD

**Issue by vivabonito** [mzakharo/librebudgeteer#1]
Hi, I wanted to clarify. I know that "secret" in the sandbox.example file under plaid-sync/config folder is supposed to be the sandbox key from the API screen on the Plaid web console, but what is public_key supposed to be? Also, are you still using this for your own budgeting needs? Or have you moved onto something else/better? Let me know. Thanks.

**Comment by mzakharo** [comment]
I remember one secret was unused. Try without it.

**Comment by vivabonito** [comment]
Yes, you are right, it is the public_key that is not required, and secret is required. It still does not work for me with all the details loaded. Plaid sync gives errors when connecting to any of my financial institutions. Based on your Notion rules, I noticed you are Canadian too. How did you get it to work with your Canadian banks/institutions?

**Comment by mzakharo** [comment]
I have only tried it with tangerine and it is working fine.
